- name: Set Prompt
  ansible.builtin.shell: set-prompt {{ component }}-{{ env }}

- name: Load maven
  ansible.builtin.include_role:
    name: common
    tasks_from: maven

- name: Install MySQL Client
  ansible.builtin.dnf:
    name: mysql
    state: installed

- name: Load SQL file
  ansible.builtin.shell: mysql -h mysql-{{ env }}.devopsdvs.online -uroot -p{{ lookup('hashi_vault', 'secret=roboshop-{{env}}/data/shipping:mysql_root_password token={{ vault_token }} url=http://vault-internal.devopsdvs.online:8200')}}
  loop:
    - schema
    - app-user
    - master-data

- name: Restart Shipping
  ansible.builtin.systemd_service:
    name: shipping
    state: restarted